### ISSUE TITLE
Font failures on clean install

### ISSUE THREAD

**Issue by joshforman** [creativetimofficial/ct-material-kit-pro-react-native#19]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Upon first load after compiling with expo start, the app loads without errors

# Current Behavior

The app loads with question marks in place of icons, and I see a bunch of console errors like this:

fontFamily "ionicons" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
at node_modules/expo/node_modules/expo-font/build/Font.js:27:29 in processFontFamily
at node_modules/react/cjs/react.development.js:365:30 in Component.prototype.setState
at node_modules/@expo/vector-icons/build/createIconSet.js:23:50 in Icon#componentDidMount
- ... 7 more stack frames from framework internals

# Failure Information (for bugs)

See above

## Steps to Reproduce

expo start from clean install

note that the current version of expo go is incompatible with the expo version in the current base repo, so I updated the version of expo in the base repo.  There were also dependency conflicts that required that I install with npm install --legacy-peer-deps.

## Context

I am running the most recent version of expo/expo go on a Ventura Mac M1.

## Failure Logs

See above

**Comment by joshforman** [comment]
The root problem here is Expo Go requiring a more recent version of expo than is in this repo.  But updating expo created a bit of a dependency cascade and got us to a place where AppLoading breaks.

It took a day, but I replaced AppLoading with SplashScreen (this part was easy) and tweaked package versions so that they all managed to play nicely with each other (this part was hard).  See the attached updated App.js and package.json, which now loads without errors.  There are some minor issues in image size rendering, but this is progress.

[updated_expo.zip](https://github.com/creativetimofficial/ct-material-kit-pro-react-native/files/11022163/updated_expo.zip)
