### ISSUE TITLE
Got an expo error from the box

### ISSUE THREAD

**Issue by maxkudla** [creativetimofficial/ct-material-kit-pro-react-native#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed
- [+] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The application should run up after `expo start`

# Current Behavior

The app is crashed

# Failure Information (for bugs)

```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Cannot find module '@expo/image-utils'
```

## Steps to Reproduce

1. npm install -g expo-cli
2. npm install
3. expo start

## Context

* Device: MacBook Pro
* Operating System: macOS High Sierra 10.13.6
* Browser and Version:
* node v10.9.0
* npm v6.2.0

## Failure Logs

Please include any relevant log snippets or files here.
```
Error: Cannot find module '@expo/image-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/@expo/xdl@55.0.3/src/AssetUtils.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by palingheorghe** [comment]
Hi @maxkudla ! That's a problem with Expo's CLI as far as I can see here: https://github.com/expo/expo-cli/issues/756 . If you update to `expo-cli v2.20.5` everything should work. 

Thanks,
Alin

**Comment by maxkudla** [comment]
Thanks @palingheorghe, it works this way.
